development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("redis://:p16cb47d57f788ddbabbcaa79d0927c9f5af6bcb5bebae292abd638d0117b2ec2@ec2-54-78-134-109.eu-west-1.compute.amazonaws.com:28979") { "redis://localhost:6379/1" } %>
  channel_prefix: Buddy_Gaming_production
